name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node 16.11
        uses: actions/setup-node@v2
        with:
          node-version: 16.11.0
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:unit
    - name: cypress testing
        uses: bahmutov/cypress-workflows/.github/workflows/standard.yml@v1
        with:
          start: 'npm start'
          wait-on: 'http://localhost:3000'

