name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node 16.11
        uses: actions/setup-node@v2
        with:
          node-version: 16.11.0
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:unit
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install: npm install
          build: npm run build
          start: npm start
          spec: cypress/ewe/tests.cy.js
